services:
  postgres:
    image: postgres:15
    container_name: stockflow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: stockflow_dev
    ports:
      - "5433:5432"
    volumes:
      - stockflow_data:/var/lib/postgresql/data

volumes:
  stockflow_data:
